image:
  file: .gitpod.Dockerfile

tasks:
  - name: Open Welcome File(s)
    command: |
      WelcomeFile='/workspace/GHCiCode/README.md'
      # gp open won't work until the IDE GUI is ready
      until gp open ${WelcomeFile}; do sleep 1; done
      # Safe to open more files from now on
      gp open '/workspace/GHCiCode/ghci-code/tutor/Tutor1.hs'
  - name: Setup Haskell Tooling
    # These will run only for Gitpod workspace pre-building
    init: |
      # ~/.ghcup will be lost across Gitpod workspace restarts,
      # install ghcup to /workspace/ so it is persisted as part of prebuilt workspace
      # Note `/workspace/.ghcup/bin` should have been added to PATH in Dockerfile
      mkdir -p /workspace/.ghcup/bin
      curl -sSL https://downloads.haskell.org/~ghcup/x86_64-linux-ghcup \
            -o /workspace/.ghcup/bin/ghcup
      chmod a+x /workspace/.ghcup/bin/ghcup
      # install ghc/cabal-install via ghcup
      ghcup upgrade
      ghcup install ghc
      ghcup install cabal
      ghcup install hls
      # set default version of GHC, or simple cmd like `ghci` and `cabal repl all` won't work
      ghcup set ghc
      # refresh cabal package index
      cabal update
      # refresh stack package index
      # stack update
    # These will run each time a new Gitpod workspace is open
    command: |
      cabal update
      # stack update
      ghcup upgrade
      # Show what's currently installed, and what's out there
      ghcup list

vscode:
  extensions:
    - justusadam.language-haskell
    - haskell.haskell
    - complyue.vscode-ghci
