image:
  file: .gitpod.Dockerfile

tasks:
  - name: Setup Haskell Tooling
    init: |
      # ~/.ghcup will be lost across Gitpod workspace restarts,
      # install ghcup to /workspace/ so it is persisted as part of prebuilt workspace
      # Note `/workspace/.ghcup/bin` should have been added to PATH in Dockerfile
      mkdir -p /workspace/.ghcup/bin
      curl -sSL https://downloads.haskell.org/~ghcup/x86_64-linux-ghcup \
            -o /workspace/.ghcup/bin/ghcup
      chmod a+x /workspace/.ghcup/bin/ghcup
      # install ghc/cabal-install via ghcup
      ghcup upgrade
      ghcup install ghc
      ghcup install cabal
      ghcup install hls
      # set default version of GHC, or simple cmd like `ghci` and `cabal repl all` won't work
      ghcup set ghc
      # refresh cabal package index
      cabal update
      # refresh stack package index
      stack update
    command: |
      # Open the welcome file(s)
      gp open '/workspace/GHCiCode/ghci-code/tutor/Tutor1.hs'

vscode:
  extensions:
    - justusadam.language-haskell
    - haskell.haskell
    - complyue.vscode-ghci
